### ISSUE TITLE
Error on CircleCI without setting COVERALLS_REPO_TOKEN

### ISSUE THREAD

**Issue by joshblum** [coveralls-clients/coveralls-python#115]
When trying to submit coverage on CircleCI I get the following error:

```
Couldn't find a repository matching this job.
'url'
```

```
$ pip freeze | grep coveralls
coveralls==1.1
```

I'm on the latest version of `coveralls` and according to the docs I don't need to set `COVERALLS_REPO_TOKEN` for CircleCI, what am I doing wrong?

**Comment by TheKevJames** [comment]
Hi there! Looks like the docs are a little unclear on this; you definitely do need to set `COVERALLS_REPO_TOKEN` when using this in CircleCI.

**Comment by joshblum** [comment]
Can the docs be amended to clear up future confusion ? :)

**Comment by TheKevJames** [comment]
This project is in a [feature freeze until a new maintainer is found](https://github.com/coagulant/coveralls-python/issues/122). Hopefully that won't take too long; we can clean up the docs as soon as @coagulant picks a new maintainer. Until then, let's leave this issue open as a reminder.

**Comment by joshblum** [comment]
@TheKevJames sounds good, thanks for helping!

**Comment by TheKevJames** [comment]
Long time coming, but finally done -- I've updated the docs to reflect how this actually works (since this issue was opened, we got a PR that lets you skip setting `COVERALLS_REPO_TOKEN` on CircleCI, so technically this ended up being expected behaviour... just a few months early :P).

**Comment by hiradyazdan** [comment]
@TheKevJames has this PR been merged? can you mention which PR you're referring to? I still get the error mentioned above.

**Comment by TheKevJames** [comment]
@hiradyazdan could you paste the entire output of running `coveralls`?

**Comment by hiradyazdan** [comment]
@TheKevJames I set my token on the command and it's working fine, but without the token, I get this:

```shell
Submitting coverage to coveralls.io...
Coverage submitted!
Couldn't find a repository matching this job.
'url'
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/coveralls/cli.py", line 75, in main
    log.info(result['url'])
KeyError: 'url'

coveralls returned exit code 2
``

**Comment by TheKevJames** [comment]
@hiradyazdan I just pushed a logging update. Could you please install the latest `coveralls-python` from Github:

    pip install -e git+https://github.com/coveralls-clients/coveralls-python.git#egg=coveralls

and then re-run in verbose mode?

    coveralls --verbose

**Comment by hiradyazdan** [comment]
@TheKevJames just tried it, not getting that error anymore! also tried it from the pypi package as well, it works perfectly fine now. Thanks!

**Comment by TheKevJames** [comment]
Glad to hear it!
