### ISSUE TITLE
AppVeyor coverage not collected together

### ISSUE THREAD

**Issue by hugovk** [coveralls-clients/coveralls-python#153]
On AppVeyor's Windows CI, I'm doing:

```yml
  - "%PYTHON%/Scripts/pip.exe install coveralls"
...
  - "%PYTHON%/Scripts/coverage.exe run --source=olefile -m nose tests"
...
  - "%PYTHON%/Scripts/coveralls.exe"
```
https://github.com/hugovk/olefile/blob/test-on-windows-ci-coveralls/appveyor.yml

I added the token as an env variable (https://github.com/coveralls-clients/coveralls-python#usage-another-ci) and it's sending coverage to Coveralls:

```
%PYTHON%/Scripts/coveralls.exe
Submitting coverage to coveralls.io...
Coverage submitted!
Job #29.1
https://coveralls.io/jobs/24587333
```
https://ci.appveyor.com/project/hugovk/olefile/build/1.0.8/job/g1mldab8ik508t7u#L83

However, there are 10 build jobs for different Python versions:
https://ci.appveyor.com/project/hugovk/olefile/build/1.0.8

And they're shown on Coveralls as 10 different builds, and not collected together, or with the 9 jobs from Travis CI. The 9 Travis jobs are collected together.

![image](https://cloud.githubusercontent.com/assets/1324225/24762334/bab87e0a-1af6-11e7-8ad9-daf0b291d4bd.png)

https://coveralls.io/repos/133880/builds

Is there something I'm missing?

**Comment by TheKevJames** [comment]
I bet this is related to #159. This is most likely related to the paths on Windows using backslashes instead of forward-slashes and no normalization happening. I'm going to mark this as a suplicate but not close it for now -- if you could confirm that the paths are "different", that would be a great help.

**Comment by hugovk** [comment]
How can I confirm the paths?

**Comment by TheKevJames** [comment]
If you run either `coveralls debug` or `coveralls --verbose`, you should see the paths being uploaded.  If you could paste the output of either of those commands, that would help with debugging.

**Comment by TheKevJames** [comment]
@hugovk this issue should now be resolved as of [release 1.5.0](https://github.com/coveralls-clients/coveralls-python/releases/tag/1.5.0).

**Comment by hugovk** [comment]
Thanks for the update and sorry for not replying earlier.

However, I'm still seeing separate reports with Coveralls 1.5.0.

Here's a build using `coveralls --verbose`. Or, because it's a PR, there were two builds on AppVeyor, and two on Travis, yet 11 reports on Coveralls.
 
![image](https://user-images.githubusercontent.com/1324225/44910538-42761000-ad2c-11e8-9819-9d50842a6691.png)


* https://ci.appveyor.com/project/hugovk/olefile/build/1.0.55
* https://ci.appveyor.com/project/hugovk/olefile/build/1.0.56
* https://travis-ci.org/hugovk/olefile/builds/422952515
* https://travis-ci.org/hugovk/olefile/builds/422952542

The AppVeyor logs contain `"name": "olefile/olefile.py"` with forward slashes in the verbose output.
