### ISSUE TITLE
Github action: uploading to coveralls fails since 12 Februari version 1.11.0 with repo_token from env (regression)

### ISSUE THREAD

**Issue by jberends** [coveralls-clients/coveralls-python#219]
with ref to #211 

Again cannot upload coverage to the coveralls using my github action.

Per the docs we expose a COVERALLS_REPO_TOKEN being stored as a secret in the repository secrets (settings > secrets). The github action workflow can be found [here](https://github.com/KE-works/pykechain/blob/master/.github/workflows/python_testing.yml)

This is the output of the last working example:

https://github.com/KE-works/pykechain/runs/440503409?check_suite_focus=true

```
Wed, 12 Feb 2020 07:36:49 GMT   pip install -U coveralls>=1.9.2
Wed, 12 Feb 2020 07:36:49 GMT   coveralls
Wed, 12 Feb 2020 07:36:49 GMT   shell: /bin/bash -e {0}
Wed, 12 Feb 2020 07:36:49 GMT   env:
Wed, 12 Feb 2020 07:36:49 GMT    pythonLocation: /opt/hostedtoolcache/Python/3.6.10/x64
Wed, 12 Feb 2020 07:36:49 GMT    COVERALLS_REPO_TOKEN: ***
Wed, 12 Feb 2020 07:36:51 GMT Submitting coverage to coveralls.io...
Wed, 12 Feb 2020 07:36:53 GMT Coverage submitted!
Wed, 12 Feb 2020 07:36:53 GMT Job ##227.1
Wed, 12 Feb 2020 07:36:53 GMT https://coveralls.io/jobs/58873985
```

Last time
https://github.com/KE-works/pykechain/runs/446018515?check_suite_focus=true

```
2020-02-14T13:33:48.8666130Z  pip install -U coveralls>=1.9.2
2020-02-14T13:33:48.8666251Z  coveralls
2020-02-14T13:33:48.8700948Z shell: /bin/bash -e {0}
2020-02-14T13:33:48.8701051Z env:
2020-02-14T13:33:48.8701153Z   pythonLocation: /opt/hostedtoolcache/Python/3.6.10/x64
2020-02-14T13:33:48.8701825Z   COVERALLS_REPO_TOKEN: ***
2020-02-14T13:33:50.6453241Z Submitting coverage to coveralls.io...
2020-02-14T13:33:51.6928459Z Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
2020-02-14T13:33:51.6929018Z Traceback (most recent call last):
2020-02-14T13:33:51.6931237Z   File "/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/coveralls/api.py", line 193, in wear
2020-02-14T13:33:51.6931659Z     response.raise_for_status()
2020-02-14T13:33:51.6932280Z   File "/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
2020-02-14T13:33:51.6932741Z     raise HTTPError(http_error_msg, response=self)
2020-02-14T13:33:51.6932901Z requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
2020-02-14T13:33:51.6933000Z 
2020-02-14T13:33:51.6933110Z During handling of the above exception, another exception occurred:
2020-02-14T13:33:51.6933171Z 
2020-02-14T13:33:51.6933274Z Traceback (most recent call last):
2020-02-14T13:33:51.6933706Z   File "/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/coveralls/cli.py", line 77, in main
2020-02-14T13:33:51.6933847Z     result = coverallz.wear()
2020-02-14T13:33:51.6934220Z   File "/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/coveralls/api.py", line 196, in wear
2020-02-14T13:33:51.6934621Z     raise CoverallsException('Could not submit coverage: {}'.format(e))
2020-02-14T13:33:51.6934793Z coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
2020-02-14T13:33:51.7142220Z Process completed with exit code 1.
```

Pinning the release of coveralls to 1.10.0 actually works.

I was wondering, how this can be prevented in the future. The use of a secrets in github actions is not that uncommon, right? Can we think of a test on it.
If I compare the two tags of the release, I cannot immediately see how the changed would affect the call to the coveralls API, (maybe that is not the problem, but the pickup of coveralls results...)

**Comment by TheKevJames** [comment]
Wow, sorry to hear we managed to flub this again -- my apologies!

$5-to-1 says that this is because we reverted the change that fixed this for you last time; it _seemed_ like it had been fixed on the Coveralls side, so we no longer needed our fix. Clearly our testcase here didn't work out for us.

I've just pushed that same fix to a branch -- could you please try installing from there? Should be 
```python
pip install git+https://github.com/coveralls-clients/coveralls-python.git@fix-github-actions
```

If that works out for you, I'll get that wrapped into a real release.

**Comment by mcdonnnj** [comment]
I was seeing this exact issue in our repo:
https://github.com/cisagov/skeleton-python-library/runs/441574150?check_suite_focus=true
```
2020-02-12T16:37:10.8508385Z env:
2020-02-12T16:37:10.8508497Z   PIP_CACHE_DIR: ~/.cache/pip
2020-02-12T16:37:10.8508594Z   PRE_COMMIT_CACHE_DIR: ~/.cache/pre-commit
2020-02-12T16:37:10.8508710Z   pythonLocation: /opt/hostedtoolcache/Python/3.8.1/x64
2020-02-12T16:37:10.8509505Z   COVERALLS_REPO_TOKEN: ***
2020-02-12T16:37:10.8509618Z ##[endgroup]
2020-02-12T16:37:10.9876531Z Submitting coverage to coveralls.io...
2020-02-12T16:37:11.3572603Z Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
2020-02-12T16:37:11.3572834Z Traceback (most recent call last):
2020-02-12T16:37:11.3574809Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/coveralls/api.py", line 193, in wear
2020-02-12T16:37:11.3575041Z     response.raise_for_status()
2020-02-12T16:37:11.3575696Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
2020-02-12T16:37:11.3575905Z     raise HTTPError(http_error_msg, response=self)
2020-02-12T16:37:11.3576068Z requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
2020-02-12T16:37:11.3576180Z 
2020-02-12T16:37:11.3576302Z During handling of the above exception, another exception occurred:
2020-02-12T16:37:11.3576372Z 
2020-02-12T16:37:11.3576483Z Traceback (most recent call last):
2020-02-12T16:37:11.3577013Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/coveralls/cli.py", line 77, in main
2020-02-12T16:37:11.3577155Z     result = coverallz.wear()
2020-02-12T16:37:11.3577539Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/coveralls/api.py", line 196, in wear
2020-02-12T16:37:11.3577934Z     raise CoverallsException('Could not submit coverage: {}'.format(e))
2020-02-12T16:37:11.3578107Z coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
2020-02-12T16:37:11.3791611Z ##[error]Process completed with exit code 1.
```

Pinning to your test branch has resulted in expected behavior:
https://github.com/cisagov/skeleton-python-library/runs/446808312?check_suite_focus=true
```
2020-02-14T20:16:39.3352970Z env:
2020-02-14T20:16:39.3353114Z   PIP_CACHE_DIR: ~/.cache/pip
2020-02-14T20:16:39.3353230Z   PRE_COMMIT_CACHE_DIR: ~/.cache/pre-commit
2020-02-14T20:16:39.3353364Z   pythonLocation: /opt/hostedtoolcache/Python/3.8.1/x64
2020-02-14T20:16:39.3354159Z   COVERALLS_REPO_TOKEN: ***
2020-02-14T20:16:39.3354297Z ##[endgroup]
2020-02-14T20:16:39.5940135Z Submitting coverage to coveralls.io...
2020-02-14T20:16:40.2107542Z Coverage submitted!
2020-02-14T20:16:40.2108437Z Job #6a7210cc3d2f0f976eec198f620d0ebfc338be57.1
2020-02-14T20:16:40.2108788Z https://coveralls.io/jobs/58992039
```

**Comment by jberends** [comment]
Great! Thanks for the commit. Will await the release. Its not about the bug itself but the ability to recover from it, right! 👍

**Comment by TheKevJames** [comment]
@jberends @fphammerle @mcdonnnj This should now be fixed: version 1.11.1 with the above fix is live on PyPI and rolling out to Conda shortly.

Sorry about this, folks!

**Comment by scarabeusiv** [comment]
@TheKevJames the uploading still fails for me even with 1.11.1 version with the same error.
If I pin the release to 1.9.1 by hand it works just fine:
 https://github.com/rpm-software-management/spec-cleaner/pull/275
I will keep this open for a bit but you can see I tried blindly various changes and nothing helped. And I export the repo token... Any ideas?

**Comment by TheKevJames** [comment]
Interesting! @scarabeusiv somehow your repo behaves the exact opposite of how the other folks' repos work; where everyone else seems to be getting a 422 when we name the job "github" and a 200 when it's "github-actions", yours is the exact opposite!

I looked through all the examples so far:
* [pykechain](https://github.com/KE-works/pykechain/runs/446018515?check_suite_focus=true): fails unless `name='github-actions'`
* [skeleton-python-library](https://github.com/cisagov/skeleton-python-library/runs/441574150?check_suite_focus=true): fails unless `name='github-actions'`
* [spec-cleaner](https://github.com/rpm-software-management/spec-cleaner/runs/503832103): fails unless `name='github'`

The only correlation I could draw is that the former two are "build on push" GH actions and the latter is "build on pull_request". Which... would be an incredibly odd thing to cause the issue, but I'll go try it anyway just in case!

**Comment by TheKevJames** [comment]
@scarabeusiv I notice you have [`COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}`](https://github.com/rpm-software-management/spec-cleaner/blob/master/.github/workflows/pythonpackage.yml#L39) set in your configuration -- that seems to be the only difference I can find here. Just sanity checking -- if you set that to the Coveralls repo token you can get from your Coveralls.io dashboard, does it then work with newer versions of this library?

**Comment by scarabeusiv** [comment]
Interesting, I've renamed the secret variable in the settings and reused it in the action to make it happy :)
https://github.com/rpm-software-management/spec-cleaner/pull/279

Lets consider it magic.

Thanks for the advice, I would really not even think to rename it but was like 'why the heck not try it :)'

**Comment by TheKevJames** [comment]
Huh, definitely magic. Alright, I'll make sure to get this into our docs! Glad to hear its working for you :)
