### ISSUE TITLE
Allow setting other service_* parameters

### ISSUE THREAD

**Issue by bmw** [coveralls-clients/coveralls-python#220]
Based on the text at the bottom of https://docs.coveralls.io/supported-ci-services, my understanding is to use Coveralls with an unsupported CI provider, you need to set the other `service_*` parameters in https://docs.coveralls.io/api-reference.

There doesn't currently appear to be a way to do this though which is preventing me from using this project.

**Comment by TheKevJames** [comment]
This library _should_ support arbitrary CI environments already to some extent -- if you set `COVERALLS_REPO_TOKEN` it should work even from your local machine. Fully integrating back to eg. capturing the CI job ID is slightly trickier.

It would indeed be a great idea to allow passing in arbitrary values so we don't need to explicitly add support for each service -- I would love to brainstorm about / accept a PR to introduce this functionality. If I find some time, I might even try to do this myself :)

In the short term, I'd also love to accept a PR for adding Azure support!

**Comment by TheKevJames** [comment]
I might be missing something here: a quick glance at the [Azure docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch) seems to imply that there are no default environment variables set. Am I missing something?

Might be this is partially a documentation issue, if that is the case, as we will need to track down which Azure variables need to get tracked as environment variables -- [this section](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables) looks promising for that.

**Comment by bmw** [comment]
The reason I'm personally interested in this is so coveralls can combine coverage reports from multiple jobs and my understanding is to do that I think they [need more information about the build](https://github.com/lemurheavy/coveralls-public/issues/544#issuecomment-403629390).

While I'd love to see out of the box support for Azure Pipelines, my suggestion for what it's worth would be to add generic configuration options for the values that Coveralls' API accepts so this client could be used with any CI provider.

With that said, if you're interested in Azure specifically, it's a little confusing, but all of the [build variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables) are defined as environment variables although from the bottom of https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax: "When variables are turned into environment variables, variable names become uppercase, and periods turn into underscores." So for instance `Build.BuildId` becomes `BUILD_BUILDID`.

If it's useful, someone got this working with another coveralls client at https://github.com/lemurheavy/coveralls-public/issues/1272#issuecomment-473455158.

**Comment by wumpus** [comment]
Here is a working recipe for using Azure PIpelines and the python coveralls client: https://github.com/coveralls-clients/coveralls-python/issues/245

**Comment by TheKevJames** [comment]
@bmw I merged @wumpus' code example into our docs, that should hopefully explain what you need!

**Comment by Silmathoron** [comment]
Hi @TheKevJames I am still unable to use coveralls with SourceHut at the moment.
I don't know whether I missed the place in the doc that tells precisely which variables should be set to use a random "unsupported" service; if so could you point me to it?
If not, should I open a new issue to discuss precisely how to do this?
Namely: what entries must be present in ``.coveralls.yml`` so that a random service will successfully post to Coveralls rather than leading to ``coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs``?

**Comment by wumpus** [comment]
@Silmathoron please see the [new documentation for using Azure Pipelines by pretending to be CircleCI.](https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#azure-pipelines-support)
